### ISSUE TITLE
about minicnc drive ramp1.4

### ISSUE THREAD

**Issue by smkj312** [aiten/CNCLib#10]
Hi,aiten
I want to make a cnc with ramp1.4. However, there was no response after burning the firmware. Does cnclib support minicnc? What should I do?
Thank you! good luck!

**Comment by aiten** [comment]
Hi,
I added CNC to a Proxxon MF70, This is the sketch MaxiCNC. Please see the configuration.h file to select a machine type (Line26ff)

**#define HARDWARETYPE HARDWARETYPE_PROXXONMF70**
//#define HARDWARETYPE HARDWARETYPE_MYCNC
//#define HARDWARETYPE HARDWARETYPE_KK1000S

Please uncomment the Proxxonline and comment all other (KK100S, MYCNC)

To get a correct communication between the machine and e.g. CNCLib you have to use the same baud rate. With ramps 1.4 the configuration is 115200 (see ConfigurationMachine_ProxxonMF70.h)
To check the communication you can also use the Arduino IDE. Start the Serial monitor and select 115200 baud. 
The default for a proxxon mf70 (with ramps1.4) is, that the machine performs a home move for all axes. This takes a while (if you have not connected the endstop switch). To avoid this reference move you can ether modify the configuration files (ConfigurationMachine_ProxxonMF70.h) or you can wirte a new configuration into the eeprom (using the CNCLib Application)


Herbert A.

**Comment by smkj312** [comment]
Thank you for your reply.
After the program is compiled, the following error occurs: （Arudino 1.8.8）
*************************
In file included from D:\cnc\Sketch\MaxiCNC\MaxiCNC\MaxiCNC.ino:23:0:
C:\Users\1\Documents\Arduino\libraries\Include/SD.h:23:22: fatal error: sys/stat.h: No such file or directory
compilation terminated.
exit status 1
**************************
Is there some library file missing? 

SD.h 

////////////////////////////////////////////////////////

#pragma once

#include <io.h>
#include <sys/types.h>
#include <sys/stat.h>

////////////////////////////////////////////////////////////

**Comment by smkj312** [comment]
In file included from C:\Users\1\Documents\Arduino\libraries\Include/FastSPI_LED.h:4:0,
                 from D:\cnc\Sketch\MaxiCNC\MaxiCNC\MaxiCNC.ino:3:
C:\Users\1\Documents\Arduino\libraries\Include/Arduino.h:27:19: fatal error: conio.h: No such file or directory
compilation terminated.
exit status 1

**Comment by aiten** [comment]
Hi, 

I think you have copied to much to your arduino library folder (C:\Users\1\Documents\Arduino\libraries). Please clean this directory.

The MaxiCNC sketch uses 3 libraries: StepperLib, CNCLib and CNCLibEx. Additionally you have to download the u8g2 library (for LCD 12864 support.)  

* Please download or clone the github repository to a new folder: e.g. **d:\CNC**
* Now you can copy the libraries (StepperLib,CNCLib and CNCLibEx) to your arduino default library path (e.g. C:\Users\1\Documents\Arduino\libraries) 
OR 
you can change the default sketch location (see Arduino IDE: Menu:File->Preferences "Sketchbook location") to **d:\CNC**\Sketch

* Now download the U8g2 library (see Arduino: Menu: Sketch->Include Library->manage Libraries
* Dont forget to specify "Arduino Mega 2560" as board type 
* Open The sketch **d:\CNC**\MaxiCNC\MaxiCNC.ino
* Change the configuration.h file to use PROXXON (see my last comment)
* Compile and download the sketch to the board.

Start the Arduino Serial Monitor to check the download. 
* Menu Tools->Serial Monitor
* use 115200 baud and Cr+LF
* you should see a wellcome message of the machine

To configure the machine (maxsize, endstop, ...) you can modifiy the sketch (and download) again 
OR 
you can use CNCLib (see github/aiten/CNCLib) to save the configuration to the eeprom of the Mega2560

**Comment by smkj312** [comment]
Thank you ！
The engraving machine is already available, and we are currently studying how cnclib can be used. 
Thanks again!
