### ISSUE TITLE
About the Plotter Limit Switch

### ISSUE THREAD

**Issue by smkj312** [aiten/CNCLib#3]
About the Plotter Limit Switch
I use the RAMP1.4 package, burning plotter firmware, (no LCD, I have the program in the LCD-related part of the comment out), but the limit switch does not work, the maximum and minimum are not action.
But the HPGL command file can be executed.
Please give me some suggestions, thank you!

**Comment by aiten** [comment]
I have changed the library to store some parameter - e.g. the referencemove - in the EEPROM.
I have not checked the plotter sample. I will do this in the next days

**Comment by smkj312** [comment]
Thank you. I'm going to look forward to your update. The In addition, can i use msplot driver to control. I am a rookie please don't mind if I childish problem.

**Comment by aiten** [comment]
I have updated the plotter sketch. Now the endstop (min or max) can be configured in the sketch or in the eeprom. 
* EEprom: use the windows app CNCLib.Wpf.start and connect to your arduino plotter. 
   With the button "EEprom" (after you are connected) you can read and modify the eeprom.
* Sketch: see configuration.h

Endstops are used at (arduino) boot time to find the current position. After boot the specified size is used to limit the movements.

I have not used the msplot driver at all. But I will look for it.

**Comment by smkj312** [comment]
New program I have tested. very good.
Thank you for paying,
Good luck!
