### ISSUE TITLE
Plotter sketch: Support SP (SelectPen) command

### ISSUE THREAD

**Issue by aiten** [aiten/CNCLib#5]
The SP command (hpgl) should be supported.
see https://en.wikipedia.org/wiki/HPGL

**Comment by smkj312** [comment]
Good job！

**Comment by aiten** [comment]
The following HPGL commands are added to the plotter sketch:
* SP "set pen", positions and behavior to change the pen is predefined. If you building your own plotter you may have to change the Eeprom values or even change the program (see: PlotterControl.cpp) – I will write a wiki.
* VS “pen speed”, as defined in the https://en.wikipedia.org/wiki/HPGL
* VN „set pen speed to normal“
